### ISSUE TITLE
Exception while loading move_group capability

### ISSUE THREAD

**Issue by metanav** [ros-planning/moveit2#1907]
### Description
I am trying to run moveit2_tutorials pick and place with task constructor demo. It was working 1 month ago but after rebuilding latest moveit2 from the source it is not working. 

### Your environment
* ROS Distro: Humble
* OS Version: MacOS Ventura 13.1
* Source build Humble branch
* Which RMW Fast DDS or Cyclone DDS)? Fast DDS

### Steps to reproduce
```
$ ros2 launch moveit2_tutorials mtc_demo.launch.py

```
### Expected behaviour
It should load all move_group capabilities.

### Actual behaviour

It is not loading  default move_group capabilities except ExecuteTaskSolution.

### Backtrace or Console output

```
[INFO] [launch]: All log files can be found below /Users/metanav/.ros/log/2023-01-29-09-01-35-187258-MacBook-Pro-5.local-5657
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [5658]
[INFO] [static_transform_publisher-2]: process started with pid [5659]
[INFO] [robot_state_publisher-3]: process started with pid [5660]
[INFO] [move_group-4]: process started with pid [5661]
[INFO] [ros2_control_node-5]: process started with pid [5662]
[INFO] [ros2 run controller_manager spawner panda_arm_controller-6]: process started with pid [5663]
[INFO] [ros2 run controller_manager spawner panda_hand_controller-7]: process started with pid [5664]
[INFO] [ros2 run controller_manager spawner joint_state_broadcaster-8]: process started with pid [5665]
[static_transform_publisher-2] [WARN] [1674950497.121819198] []: Old-style arguments are deprecated; see --help for new-style arguments
[ros2_control_node-5] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class mock_components::GenericSystem. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[ros2_control_node-5]          at line 261 in /Users/naveen/ros2_humble/install/class_loader/include/class_loader/class_loader/class_loader_core.hpp
[ros2_control_node-5] [INFO] [1674950498.971993492] [resource_manager]: Loading hardware 'PandaFakeSystem' 
[ros2_control_node-5] [INFO] [1674950499.301312892] [resource_manager]: Initialize hardware 'PandaFakeSystem' 
[ros2_control_node-5] [WARN] [1674950499.302676092] [mock_generic_system]: Parsing of optional initial interface values failed or uses a deprecated format. Add initial values for every state interface in the ros2_control.xacro. For example: 
[ros2_control_node-5] <state_interface name="velocity"> 
[ros2_control_node-5]   <param name="initial_value">0.0</param> 
[ros2_control_node-5] </state_interface>
[ros2_control_node-5] [INFO] [1674950499.302780383] [resource_manager]: Successful initialization of hardware 'PandaFakeSystem'
[ros2_control_node-5] [INFO] [1674950499.302837542] [resource_manager]: Loading hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1674950499.302892411] [resource_manager]: Initialize hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1674950499.302920941] [resource_manager]: Successful initialization of hardware 'PandaHandFakeSystem'
[ros2_control_node-5] [INFO] [1674950499.302989157] [resource_manager]: 'configure' hardware 'PandaFakeSystem' 
[ros2_control_node-5] [INFO] [1674950499.303009062] [resource_manager]: Successful 'configure' of hardware 'PandaFakeSystem'
[ros2_control_node-5] [INFO] [1674950499.303030943] [resource_manager]: 'activate' hardware 'PandaFakeSystem' 
[ros2_control_node-5] [INFO] [1674950499.303047127] [resource_manager]: Successful 'activate' of hardware 'PandaFakeSystem'
[ros2_control_node-5] [INFO] [1674950499.303062429] [resource_manager]: 'configure' hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1674950499.303077566] [resource_manager]: Successful 'configure' of hardware 'PandaHandFakeSystem'
[ros2_control_node-5] [INFO] [1674950499.303170713] [resource_manager]: 'activate' hardware 'PandaHandFakeSystem' 
[ros2_control_node-5] [INFO] [1674950499.303194443] [resource_manager]: Successful 'activate' of hardware 'PandaHandFakeSystem'
[static_transform_publisher-2] [INFO] [1674950500.101910572] [static_transform_publisher]: Spinning until stopped - publishing transform
[static_transform_publisher-2] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-2] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-2] from 'world' to 'panda_link0'
[ros2 run controller_manager spawner panda_hand_controller-7] [INFO] [1674950500.921881192] [spawner_panda_hand_controller]: Waiting for '/controller_manager' services to be available
[ros2 run controller_manager spawner panda_arm_controller-6] [INFO] [1674950500.925889322] [spawner_panda_arm_controller]: Waiting for '/controller_manager' services to be available
[ros2 run controller_manager spawner joint_state_broadcaster-8] [INFO] [1674950501.095665863] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' services to be available
[robot_state_publisher-3] [INFO] [1674950501.192334341] [robot_state_publisher]: got segment panda_hand
[robot_state_publisher-3] [INFO] [1674950501.192435700] [robot_state_publisher]: got segment panda_leftfinger
[robot_state_publisher-3] [INFO] [1674950501.192468637] [robot_state_publisher]: got segment panda_link0
[robot_state_publisher-3] [INFO] [1674950501.192494780] [robot_state_publisher]: got segment panda_link1
[robot_state_publisher-3] [INFO] [1674950501.192518676] [robot_state_publisher]: got segment panda_link2
[robot_state_publisher-3] [INFO] [1674950501.192541083] [robot_state_publisher]: got segment panda_link3
[robot_state_publisher-3] [INFO] [1674950501.192565797] [robot_state_publisher]: got segment panda_link4
[robot_state_publisher-3] [INFO] [1674950501.192593962] [robot_state_publisher]: got segment panda_link5
[robot_state_publisher-3] [INFO] [1674950501.192618472] [robot_state_publisher]: got segment panda_link6
[robot_state_publisher-3] [INFO] [1674950501.192641388] [robot_state_publisher]: got segment panda_link7
[robot_state_publisher-3] [INFO] [1674950501.192664813] [robot_state_publisher]: got segment panda_link8
[robot_state_publisher-3] [INFO] [1674950501.192688115] [robot_state_publisher]: got segment panda_rightfinger
[rviz2-1] [INFO] [1674950501.835921182] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1674950501.836057833] [rviz2]: OpenGl version: 2.1 (GLSL 1.2)
[rviz2-1] [INFO] [1674950501.970517214] [rviz2]: Stereo is NOT SUPPORTED
[ros2_control_node-5] [INFO] [1674950502.805922394] [controller_manager]: update rate is 100 Hz
[ros2_control_node-5] [INFO] [1674950502.806419163] [controller_manager]: RT kernel is recommended for better performance
[ros2_control_node-5] [INFO] [1674950502.814210345] [controller_manager]: Loading controller 'joint_state_broadcaster'
[ros2_control_node-5] [INFO] [1674950503.268191796] [controller_manager]: Loading controller 'panda_hand_controller'
[ros2_control_node-5] [ERROR] [1674950503.268271033] [controller_manager]: Loader for controller 'panda_hand_controller' (type 'position_controllers/GripperActionController') not found.
[ros2_control_node-5] [INFO] [1674950503.268304660] [controller_manager]: Available classes:
[ros2_control_node-5] [INFO] [1674950503.268337150] [controller_manager]:   controller_manager/test_controller
[ros2_control_node-5] [INFO] [1674950503.268363903] [controller_manager]:   controller_manager/test_controller_failed_init
[ros2_control_node-5] [INFO] [1674950503.268387633] [controller_manager]:   controller_manager/test_controller_with_interfaces
[ros2_control_node-5] [INFO] [1674950503.268412051] [controller_manager]:   diff_drive_controller/DiffDriveController
[ros2_control_node-5] [INFO] [1674950503.268438580] [controller_manager]:   effort_controllers/JointGroupEffortController
[ros2_control_node-5] [INFO] [1674950503.268467438] [controller_manager]:   force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
[ros2_control_node-5] [INFO] [1674950503.268493104] [controller_manager]:   forward_command_controller/ForwardCommandController
[ros2_control_node-5] [INFO] [1674950503.268518109] [controller_manager]:   forward_command_controller/MultiInterfaceForwardCommandController
[ros2_control_node-5] [INFO] [1674950503.268545706] [controller_manager]:   imu_sensor_broadcaster/IMUSensorBroadcaster
[ros2_control_node-5] [INFO] [1674950503.268572553] [controller_manager]:   joint_state_broadcaster/JointStateBroadcaster
[ros2_control_node-5] [INFO] [1674950503.268598778] [controller_manager]:   joint_trajectory_controller/JointTrajectoryController
[ros2_control_node-5] [INFO] [1674950503.268625978] [controller_manager]:   position_controllers/JointGroupPositionController
[ros2_control_node-5] [INFO] [1674950503.268654037] [controller_manager]:   tricycle_controller/TricycleController
[ros2_control_node-5] [INFO] [1674950503.268681525] [controller_manager]:   velocity_controllers/JointGroupVelocityController
[ros2_control_node-5] [INFO] [1674950503.268719883] [controller_manager]:   admittance_controller/AdmittanceController
[ros2_control_node-5] [INFO] [1674950503.268748502] [controller_manager]:   controller_manager/test_chainable_controller
[ros2_control_node-5] [INFO] [1674950503.269183762] [controller_manager]: Loading controller 'panda_arm_controller'
[ros2 run controller_manager spawner joint_state_broadcaster-8] [INFO] [1674950503.270762665] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ros2_control_node-5] [INFO] [1674950503.354395611] [joint_trajectory_controller.interpolation_methods]: No interpolation method parameter was given. Using the default, VARIABLE_DEGREE_SPLINE.
[ros2_control_node-5] [INFO] [1674950503.356902362] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ros2_control_node-5] [INFO] [1674950503.357123819] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[ros2 run controller_manager spawner panda_arm_controller-6] [INFO] [1674950503.362069115] [spawner_panda_arm_controller]: Loaded panda_arm_controller
[ros2 run controller_manager spawner panda_hand_controller-7] [ros2run]: Process exited with failure 1
[ERROR] [ros2 run controller_manager spawner panda_hand_controller-7]: process has died [pid 5664, exit code 1, cmd 'ros2 run controller_manager spawner panda_hand_controller'].
[ros2_control_node-5] [INFO] [1674950504.455543022] [controller_manager]: Configuring controller 'panda_arm_controller'
[ros2_control_node-5] [INFO] [1674950504.455964285] [panda_arm_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ros2_control_node-5] [INFO] [1674950504.456022638] [panda_arm_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[ros2_control_node-5] [INFO] [1674950504.456068712] [joint_trajectory_controller.interpolation_methods]: No interpolation method parameter was given. Using the default, VARIABLE_DEGREE_SPLINE.
[ros2_control_node-5] [INFO] [1674950504.456092992] [panda_arm_controller]: Using 'splines' interpolation method.
[ros2_control_node-5] [INFO] [1674950504.951818731] [panda_arm_controller]: Controller state will be published at 50.00 Hz.
[move_group-4] [INFO] [1674950505.317777182] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0364269 seconds
[move_group-4] [INFO] [1674950505.317832870] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[ros2_control_node-5] [INFO] [1674950505.414124070] [panda_arm_controller]: Action status changes will be monitored at 20.00 Hz.
[rviz2-1] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-1]          at line 261 in /Users/naveen/ros2_humble/install/class_loader/include/class_loader/class_loader/class_loader_core.hpp
[ros2 run controller_manager spawner joint_state_broadcaster-8] [INFO] [1674950506.819248667] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[ros2 run controller_manager spawner panda_arm_controller-6] [INFO] [1674950506.839609126] [spawner_panda_arm_controller]: Configured and activated panda_arm_controller
[INFO] [ros2 run controller_manager spawner joint_state_broadcaster-8]: process has finished cleanly [pid 5665]
[INFO] [ros2 run controller_manager spawner panda_arm_controller-6]: process has finished cleanly [pid 5663]
[move_group-4] [INFO] [1674950507.597256290] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-4] [INFO] [1674950507.597389166] [moveit.ros_planning_interface.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-4] [INFO] [1674950508.196049615] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[rviz2-1] [INFO] [1674950508.325727524] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0305219 seconds
[rviz2-1] [INFO] [1674950508.325785029] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[move_group-4] [INFO] [1674950508.853513370] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-4] [INFO] [1674950508.853555976] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[move_group-4] [INFO] [1674950508.853938418] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-4] [INFO] [1674950508.853965745] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-4] [INFO] [1674950509.511285456] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
[move_group-4] [INFO] [1674950510.189177972] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-4] [WARN] [1674950510.211319692] [moveit.ros.occupancy_map_monitor.middleware_handle]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-4] [ERROR] [1674950510.211372737] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
[move_group-4] [INFO] [1674950510.852070651] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'ompl'
[move_group-4] [INFO] [1674950511.168899599] [moveit.ros_planning.planning_pipeline]: Using planning interface 'OMPL'
[move_group-4] [INFO] [1674950511.983024359] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.path_tolerance' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1674950511.983067337] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.resample_dt' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1674950511.983083551] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.min_angle_change' was not set. Using default value: 0.001000
[move_group-4] [INFO] [1674950511.983208553] [moveit_ros.fix_workspace_bounds]: Param 'ompl.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-4] [INFO] [1674950511.983295099] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_bounds_error' was set to 0.100000
[move_group-4] [INFO] [1674950511.983320213] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1674950511.983416456] [moveit_ros.fix_start_state_collision]: Param 'ompl.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1674950511.983442364] [moveit_ros.fix_start_state_collision]: Param 'ompl.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-4] [INFO] [1674950511.983463584] [moveit_ros.fix_start_state_collision]: Param 'ompl.max_sampling_attempts' was not set. Using default value: 100
[move_group-4] [INFO] [1674950511.983562553] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
[move_group-4] [INFO] [1674950511.983582854] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Resolve constraint frames to robot links'
[move_group-4] [INFO] [1674950511.983601929] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-4] [INFO] [1674950511.983619238] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-4] [INFO] [1674950511.983635142] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-4] [INFO] [1674950511.983651774] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[move_group-4] [INFO] [1674950514.051618965] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'pilz_industrial_motion_planner'
[move_group-4] [INFO] [1674950514.288531931] [moveit.pilz_industrial_motion_planner.joint_limits_aggregator]: Reading limits from namespace robot_description_planning
[move_group-4] [WARN] [1674950514.290732090] [moveit.pilz_industrial_motion_planner.joint_limits_aggregator]: Multi-DOF-Joint 'virtual_joint' not supported.
[move_group-4] [WARN] [1674950514.290772553] [moveit.pilz_industrial_motion_planner.joint_limits_aggregator]: Multi-DOF-Joint 'virtual_joint' not supported.
[move_group-4] [INFO] [1674950514.322320711] [moveit.pilz_industrial_motion_planner]: Available plugins: pilz_industrial_motion_planner/PlanningContextLoaderCIRC pilz_industrial_motion_planner/PlanningContextLoaderLIN pilz_industrial_motion_planner/PlanningContextLoaderPTP 
[move_group-4] [INFO] [1674950514.322358857] [moveit.pilz_industrial_motion_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderCIRC
[move_group-4] [INFO] [1674950514.334775550] [moveit.pilz_industrial_motion_planner]: Registered Algorithm [CIRC]
[move_group-4] [INFO] [1674950514.334809274] [moveit.pilz_industrial_motion_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderLIN
[move_group-4] [INFO] [1674950514.346681894] [moveit.pilz_industrial_motion_planner]: Registered Algorithm [LIN]
[move_group-4] [INFO] [1674950514.346720368] [moveit.pilz_industrial_motion_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderPTP
[move_group-4] [INFO] [1674950514.359257317] [moveit.pilz_industrial_motion_planner]: Registered Algorithm [PTP]
[move_group-4] [INFO] [1674950514.359303566] [moveit.ros_planning.planning_pipeline]: Using planning interface 'Pilz Industrial Motion Planner'
[move_group-4] [INFO] [1674950514.409562721] [moveit_ros.fix_workspace_bounds]: Param 'pilz_industrial_motion_planner.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-4] [INFO] [1674950514.409679902] [moveit_ros.fix_start_state_bounds]: Param 'pilz_industrial_motion_planner.start_state_max_bounds_error' was not set. Using default value: 0.050000
[move_group-4] [INFO] [1674950514.409697971] [moveit_ros.fix_start_state_bounds]: Param 'pilz_industrial_motion_planner.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1674950514.409793433] [moveit_ros.fix_start_state_collision]: Param 'pilz_industrial_motion_planner.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1674950514.409809145] [moveit_ros.fix_start_state_collision]: Param 'pilz_industrial_motion_planner.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-4] [INFO] [1674950514.409823319] [moveit_ros.fix_start_state_collision]: Param 'pilz_industrial_motion_planner.max_sampling_attempts' was not set. Using default value: 100
[move_group-4] [INFO] [1674950514.409915561] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-4] [INFO] [1674950514.409928565] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-4] [INFO] [1674950514.409939178] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-4] [INFO] [1674950514.409949649] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[move_group-4] [INFO] [1674950514.410584963] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'trajopt'
[move_group-4] [ERROR] [1674950514.460682574] [moveit.ros_planning.planning_pipeline]: Exception while loading planner 'trajopt_interface/TrajOptPlanner': According to the loaded plugin descriptions the class trajopt_interface/TrajOptPlanner with base class type planning_interface::PlannerManager does not exist. Declared types are  chomp_interface/CHOMPPlanner ompl_interface/OMPLPlanner pilz_industrial_motion_planner/CommandPlannerAvailable plugins: chomp_interface/CHOMPPlanner, ompl_interface/OMPLPlanner, pilz_industrial_motion_planner/CommandPlanner
[move_group-4] [INFO] [1674950514.509033140] [moveit_ros.add_time_optimal_parameterization]: Param 'trajopt.path_tolerance' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1674950514.509078980] [moveit_ros.add_time_optimal_parameterization]: Param 'trajopt.resample_dt' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1674950514.509181390] [moveit_ros.add_time_optimal_parameterization]: Param 'trajopt.min_angle_change' was not set. Using default value: 0.001000
[move_group-4] [INFO] [1674950514.509335999] [moveit_ros.fix_workspace_bounds]: Param 'trajopt.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-4] [INFO] [1674950514.509479272] [moveit_ros.fix_start_state_bounds]: Param 'trajopt.start_state_max_bounds_error' was set to 0.100000
[move_group-4] [INFO] [1674950514.509505078] [moveit_ros.fix_start_state_bounds]: Param 'trajopt.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1674950514.509637021] [moveit_ros.fix_start_state_collision]: Param 'trajopt.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1674950514.509661379] [moveit_ros.fix_start_state_collision]: Param 'trajopt.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-4] [INFO] [1674950514.509683821] [moveit_ros.fix_start_state_collision]: Param 'trajopt.max_sampling_attempts' was not set. Using default value: 100
[move_group-4] [INFO] [1674950514.509816419] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
[move_group-4] [INFO] [1674950514.509838056] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-4] [INFO] [1674950514.509855366] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-4] [INFO] [1674950514.509871631] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-4] [INFO] [1674950514.509887423] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[move_group-4] [ERROR] [1674950514.510743730] [moveit.ros_planning_interface.moveit_cpp]: Failed to initialize planning pipeline 'trajopt'.
[move_group-4] [INFO] [1674950514.511353290] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'chomp'
[move_group-4] [INFO] [1674950514.600513509] [moveit.ros_planning.planning_pipeline]: Using planning interface 'CHOMP'
[move_group-4] [INFO] [1674950514.649660338] [moveit_ros.add_time_optimal_parameterization]: Param 'chomp.path_tolerance' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1674950514.649700872] [moveit_ros.add_time_optimal_parameterization]: Param 'chomp.resample_dt' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1674950514.649721796] [moveit_ros.add_time_optimal_parameterization]: Param 'chomp.min_angle_change' was not set. Using default value: 0.001000
[move_group-4] [INFO] [1674950514.649858954] [moveit_ros.fix_workspace_bounds]: Param 'chomp.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-4] [INFO] [1674950514.650002904] [moveit_ros.fix_start_state_bounds]: Param 'chomp.start_state_max_bounds_error' was set to 0.100000
[move_group-4] [INFO] [1674950514.650027054] [moveit_ros.fix_start_state_bounds]: Param 'chomp.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1674950514.650161899] [moveit_ros.fix_start_state_collision]: Param 'chomp.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1674950514.650185081] [moveit_ros.fix_start_state_collision]: Param 'chomp.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-4] [INFO] [1674950514.650204306] [moveit_ros.fix_start_state_collision]: Param 'chomp.max_sampling_attempts' was not set. Using default value: 100
[move_group-4] [INFO] [1674950514.650338866] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
[move_group-4] [INFO] [1674950514.650358402] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-4] [INFO] [1674950514.650374765] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-4] [INFO] [1674950514.650391208] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-4] [INFO] [1674950514.650406611] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[move_group-4] [INFO] [1674950514.651184309] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'lerp'
[move_group-4] [ERROR] [1674950514.702839819] [moveit.ros_planning.planning_pipeline]: Exception while loading planner 'lerp_interface/LERPPlanner': According to the loaded plugin descriptions the class lerp_interface/LERPPlanner with base class type planning_interface::PlannerManager does not exist. Declared types are  chomp_interface/CHOMPPlanner ompl_interface/OMPLPlanner pilz_industrial_motion_planner/CommandPlannerAvailable plugins: chomp_interface/CHOMPPlanner, ompl_interface/OMPLPlanner, pilz_industrial_motion_planner/CommandPlanner
[move_group-4] [INFO] [1674950514.753692596] [moveit_ros.add_time_optimal_parameterization]: Param 'lerp.path_tolerance' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1674950514.753728381] [moveit_ros.add_time_optimal_parameterization]: Param 'lerp.resample_dt' was not set. Using default value: 0.100000
[move_group-4] [INFO] [1674950514.753744689] [moveit_ros.add_time_optimal_parameterization]: Param 'lerp.min_angle_change' was not set. Using default value: 0.001000
[move_group-4] [INFO] [1674950514.753848370] [moveit_ros.fix_workspace_bounds]: Param 'lerp.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-4] [INFO] [1674950514.753991625] [moveit_ros.fix_start_state_bounds]: Param 'lerp.start_state_max_bounds_error' was set to 0.100000
[move_group-4] [INFO] [1674950514.754013850] [moveit_ros.fix_start_state_bounds]: Param 'lerp.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1674950514.754144066] [moveit_ros.fix_start_state_collision]: Param 'lerp.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-4] [INFO] [1674950514.754165910] [moveit_ros.fix_start_state_collision]: Param 'lerp.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-4] [INFO] [1674950514.754186768] [moveit_ros.fix_start_state_collision]: Param 'lerp.max_sampling_attempts' was not set. Using default value: 100
[move_group-4] [INFO] [1674950514.754320314] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
[move_group-4] [INFO] [1674950514.754343342] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-4] [INFO] [1674950514.754360406] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-4] [INFO] [1674950514.754376940] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-4] [INFO] [1674950514.754393600] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[move_group-4] [ERROR] [1674950514.755139987] [moveit.ros_planning_interface.moveit_cpp]: Failed to initialize planning pipeline 'lerp'.
[move_group-4] [INFO] [1674950516.953607275] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for panda_arm_controller
[move_group-4] [INFO] [1674950516.954144623] [moveit.plugins.moveit_simple_controller_manager]: Max effort set to 0.0
[move_group-4] [INFO] [1674950517.146192986] [moveit.plugins.moveit_simple_controller_manager]: Added GripperCommand controller for panda_hand_controller
[move_group-4] [INFO] [1674950517.146415838] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-4] [INFO] [1674950517.146458480] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-4] [INFO] [1674950518.255072847] [moveit_ros.trajectory_execution_manager]: Trajectory execution is managing controllers
[move_group-4] [INFO] [1674950518.255124082] [move_group.move_group]: MoveGroup debug mode is ON
[move_group-4] [ERROR] [1674950519.556807809] [move_group.move_group]: Exception while loading move_group capability 'move_group/ApplyPlanningSceneService': MultiLibraryClassLoader: Could not create object of class type move_group::ApplyPlanningSceneService as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[move_group-4] [ERROR] [1674950519.560767024] [move_group.move_group]: Exception while loading move_group capability 'move_group/ClearOctomapService': MultiLibraryClassLoader: Could not create object of class type move_group::ClearOctomapService as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[move_group-4] [ERROR] [1674950519.893477601] [move_group.move_group]: Exception while loading move_group capability 'move_group/MoveGroupCartesianPathService': MultiLibraryClassLoader: Could not create object of class type move_group::MoveGroupCartesianPathService as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[move_group-4] [ERROR] [1674950519.898292080] [move_group.move_group]: Exception while loading move_group capability 'move_group/MoveGroupExecuteTrajectoryAction': MultiLibraryClassLoader: Could not create object of class type move_group::MoveGroupExecuteTrajectoryAction as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[move_group-4] [ERROR] [1674950519.902719780] [move_group.move_group]: Exception while loading move_group capability 'move_group/MoveGroupGetPlanningSceneService': MultiLibraryClassLoader: Could not create object of class type move_group::MoveGroupGetPlanningSceneService as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[move_group-4] [ERROR] [1674950519.906225898] [move_group.move_group]: Exception while loading move_group capability 'move_group/MoveGroupKinematicsService': MultiLibraryClassLoader: Could not create object of class type move_group::MoveGroupKinematicsService as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[move_group-4] [ERROR] [1674950519.909389472] [move_group.move_group]: Exception while loading move_group capability 'move_group/MoveGroupMoveAction': MultiLibraryClassLoader: Could not create object of class type move_group::MoveGroupMoveAction as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[move_group-4] [ERROR] [1674950519.912368214] [move_group.move_group]: Exception while loading move_group capability 'move_group/MoveGroupPlanService': MultiLibraryClassLoader: Could not create object of class type move_group::MoveGroupPlanService as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[move_group-4] [ERROR] [1674950519.915718827] [move_group.move_group]: Exception while loading move_group capability 'move_group/MoveGroupQueryPlannersService': MultiLibraryClassLoader: Could not create object of class type move_group::MoveGroupQueryPlannersService as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[move_group-4] [ERROR] [1674950519.920135486] [move_group.move_group]: Exception while loading move_group capability 'move_group/MoveGroupStateValidationService': MultiLibraryClassLoader: Could not create object of class type move_group::MoveGroupStateValidationService as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[move_group-4] [INFO] [1674950519.920173976] [move_group.move_group]: 
[move_group-4] 
[move_group-4] ********************************************************
[move_group-4] * MoveGroup using: 
[move_group-4] *     - ExecuteTaskSolution
[move_group-4] ********************************************************
[move_group-4] 
[move_group-4] [INFO] [1674950519.920207499] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[move_group-4] [INFO] [1674950519.920226130] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context initialization complete
[move_group-4] Loading 'move_group/ApplyPlanningSceneService'...
[move_group-4] Loading 'move_group/ClearOctomapService'...
[move_group-4] Loading 'move_group/ExecuteTaskSolutionCapability'...
[move_group-4] Loading 'move_group/MoveGroupCartesianPathService'...
[move_group-4] Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
[move_group-4] Loading 'move_group/MoveGroupGetPlanningSceneService'...
[move_group-4] Loading 'move_group/MoveGroupKinematicsService'...
[move_group-4] Loading 'move_group/MoveGroupMoveAction'...
[move_group-4] Loading 'move_group/MoveGroupPlanService'...
[move_group-4] Loading 'move_group/MoveGroupQueryPlannersService'...
[move_group-4] Loading 'move_group/MoveGroupStateValidationService'...
[move_group-4] 
[move_group-4] You can start planning now!
[move_group-4] 
[rviz2-1] [INFO] [1674950539.978998814] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.025719 seconds
[rviz2-1] [INFO] [1674950539.979034203] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-1] [WARN] [1674950540.095959963] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!
[rviz2-1] [INFO] [1674950540.176047528] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[rviz2-1] [INFO] [1674950542.280727578] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[rviz2-1] [INFO] [1674950548.370510016] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Failed to call service get_planning_scene, have you launched move_group or called psm.providePlanningSceneService()?

```

**Comment by metanav** [comment]
I removed ROS2 humble and MoveIt2 and did a fresh installation but still have same issue. Any hints where should I look to fix these errors?

**Comment by JafarAbdi** [comment]
Have you tried switching to cyclonddds? https://github.com/ros-planning/moveit2/issues/1874

**Comment by metanav** [comment]
> Have you tried switching to cyclonddds? #1874

I have already tried with `export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp` but it did not work.

**Comment by metanav** [comment]
Any updates on this?

**Comment by JafarAbdi** [comment]
@metanav Sorry I didn't have time to look into this. Were you able to fix the issue?

**Comment by okvik** [comment]
@JafarAbdi I'm encountering the same issue. Took me a while to find this report. Initially I thought the issue might be caused by something in my ROS package management setup (using Nix, i.e. `nix-ros-overlay`), but apparently not. Here's my issue in the packages repo: https://github.com/lopsided98/nix-ros-overlay/issues/264

An interesting thing I encountered is that listing capabilities through provided utility works just fine, while move_group itself doesn't find the same plugins.
 
```
$ ros2 run moveit_ros_move_group list_move_group_capabilities

Available capabilities:
move_group/ApplyPlanningSceneService
move_group/ClearOctomapService
move_group/MoveGroupCartesianPathService
move_group/MoveGroupExecuteService
move_group/MoveGroupExecuteTrajectoryAction
move_group/MoveGroupGetPlanningSceneService
move_group/MoveGroupKinematicsService
move_group/MoveGroupMoveAction
move_group/MoveGroupPlanService
move_group/MoveGroupQueryPlannersService
move_group/MoveGroupStateValidationService
move_group/TfPublisher
pilz_industrial_motion_planner/MoveGroupSequenceAction
pilz_industrial_motion_planner/MoveGroupSequenceService
```

I'm gonna try using rolling for the moment. I'll also try changing the RMW, as mentioned above.

**Comment by okvik** [comment]
Update: neither switching to rolling release nor changing RMW helped the case. I'll dive deeper next week.

**Comment by metanav** [comment]
@okvik any updates?

**Comment by okvik** [comment]
@metanav Sorry, I haven't found further clues regarding this problem.

FWIW MoveIt2 works just fine for me in a standard documented (Ubuntu) setup, I've only had this issue with the Nix packaging of it.

**Comment by sjahr** [comment]
@metanav I hope your issue is resolved by now. If not feel free to re-open this issue if it is not the case.

**Comment by metanav** [comment]
It's not resolved yet. Recently I have done a fresh installation on a new macOS Sonoma 14.1.1 but it shows same errors.

**Comment by rcruzoliver** [comment]
Hello everyone, 

I had this issue and found the reason behind. The main branch of [moveIt tutorial](https://github.com/ros-planning/moveit2_tutorials) is not correct for "humble". 

When following this [tutorial](https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html) you should clone the "humble" branch. So

```bash
git clone -b humble https://github.com/ros-planning/moveit2_tutorials
```
and then:
```bash
vcs import < moveit2_tutorials/moveit2_tutorials.repos
sudo apt update && rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
```
Be sure you start with a clean workspace and do not try to reuse the old one. 

Regards, 
Raul

**Comment by usmanbiu** [comment]
> Hello everyone,
> 
> I had this issue and found the reason behind. The main branch of [moveIt tutorial](https://github.com/ros-planning/moveit2_tutorials) is not correct for "humble".
> 
> When following this [tutorial](https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html) you should clone the "humble" branch. So
> 
> ```shell
> git clone -b humble https://github.com/ros-planning/moveit2_tutorials
> ```
> 
> and then:
> 
> ```shell
> vcs import < moveit2_tutorials/moveit2_tutorials.repos
> sudo apt update && rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
> ```
> 
> Be sure you start with a clean workspace and do not try to reuse the old one.
> 
> Regards, Raul

I had the same issue and your suggestion to clone the humble branch worked. The only difference is that in my case, I had cloned the moveit2 repo in an already existing workspace with many packages. I only had to delete the install and build folders in my workspace, I built the workspace again before closing moveit2 to a folder I created (in my workspace). Everything worked fine after that. 

PS. I followed the instructions in the moveit2 documentation for my installation but I cloned the humble branch of moveit2

**Comment by rcruzoliver** [comment]
> > Hello everyone,
> > I had this issue and found the reason behind. The main branch of [moveIt tutorial](https://github.com/ros-planning/moveit2_tutorials) is not correct for "humble".
> > When following this [tutorial](https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html) you should clone the "humble" branch. So
> > ```shell
> > git clone -b humble https://github.com/ros-planning/moveit2_tutorials
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then:
> > ```shell
> > vcs import < moveit2_tutorials/moveit2_tutorials.repos
> > sudo apt update && rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Be sure you start with a clean workspace and do not try to reuse the old one.
> > Regards, Raul
> 
> I had the same issue and your suggestion to clone the humble branch worked. The only difference is that in my case, I had cloned the moveit2 repo in an already existing workspace with many packages. I only had to delete the install and build folders in my workspace, I built the workspace again before closing moveit2 to a folder I created (in my workspace). Everything worked fine after that.
> 
> PS. I followed the instructions in the moveit2 documentation for my installation but I cloned the humble branch of moveit2

That's great. What I meant as "clean workspace" is exactly what you did: delete the install and build directories...colcon isnt otherwise fresh building the package with the new code.
